import json

# TO RUN THIS
# Place the postman collection at the same level of the folder where this file runs
# add in the key to the authorization to be added to the test (line 54 "KEY-HERE")
# change xovisdata.postman_collection.json to the collection name (line 60)

def print_start():
    print(";-----------------------------------------------------------------------------")
    print(";- HostMonitor`s export/import file                                          -")
    print(";- Generated by RCC 6.98 at 3/6/2020 1:57:51 PM                              -")
    # print(";- Source file: C:\ProgramData\HostMonitor\MAC.hml                           -")
    print(";- Generation mode: Current_Folder_Only                                      -")
    print(";-----------------------------------------------------------------------------")
    print("")
    print(";-----------------------------------------------------------------------------")
    # print("; Folder: Root\MuleSoft Enterprise Cluster\apis\checkpoint-security-api\")
    print(";-----------------------------------------------------------------------------")
    print(";You may uncomment the following line to import tests exactly into src. folder")
    # print(";DefaultFolder = Root\MuleSoft Enterprise Cluster\apis\checkpoint-security-api\")
    print("")
    print("")

def print_test(api,test_num):
    print("; ------- Test #"+test_num+" -------")
    print("")
    print("")
    print("Method      = Url")
    print(";--- Common properties ---")
    # print(r"DestFolder = Root\MuleSoft Enterprise Cluster\apis\", end='\n')
    print("Title       = /"+api[2]+" - PRD Load Balancer")
    print("Comment     = "+api[1])
    print("RelatedURL  = ")
    print("NamePattern = %object% - PRD Load Balancer")
    print("CmntPattern = %path%")
    print("ScheduleMode= Regular")
    print("Schedule    = ")
    print("Interval    = 60")
    print("Alerts      = dk_test")
    print("ReverseAlert= No")
    print("UnknownIsBad= Yes")
    print("WarningIsBad= Yes")
    print("PrivLogMode = Default")
    print("CommLogMode = Default")
    print("MasterAFresh= No")
    print(";--- Test specific properties ---")
    print("URL         = " + str(api[1]))
    print("UrlUseMacros= No")
    print("is302ok     = Yes")
    print("IgnoreUnknCA= No")
    print("CSumMode    = None")
    print("UseFrames   = No")
    print("UseImages   = No")
    print("OptHeaders  = Authorization: KEY-HERE")
    print("")
    print("")


apis = []

with open("xovisdata.postman_collection.json", "r") as json_file:
    j_file = json.load(json_file)
    app_name = j_file['info']['name']
    for item in j_file['item']:
        if('method' in item['request'] and item['request']['method'] == 'GET'):
            full_path = item['name']
            endpoint = full_path.split("/")[-1]
            apis.append((app_name,full_path,endpoint))
        # print(item)

test_num = 1
print_start()
for api in apis:
    # print(url,test_num)
    # print("{:02d}".format(test_num))
    print_test(api,"{:02d}".format(test_num))
    test_num +=1
